#
# https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy & https://docs.linuxserver.io/images/docker-swag
# need dockerproxy for auto mapping security
#
--- 
version: '3.7'
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - POST=0
#
networks:
  default:
    name: ${CONNET}
    external: true