#
# https://docs.linuxserver.io/images/docker-swag
#
--- 
version: '3.7'
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file: stack.env #used by portainer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - VALIDATION=${VALIDATION}
      - SUBDOMAINS=${SUBDOMAINS}
      - CERTPROVIDER=${CERTPROVIDER}
      - DNSPLUGIN=${DNSPLUGIN}
      - PROPAGATION=${PROPAGATION}
      - EMAIL=${EMAIL}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      - EXTRA_DOMAINS=${EXTRA_DOMAINS}
      - STAGING=${STAGING}
      - DOCKER_MODS=${DOCKER_MODS}
    volumes:
      - ${LOCVOL1}/${APPVOLDIR}:/config
    ports:
      - 443:443
      - 80:80
      # Add any other Stream port you want to expose
      - '21:21' # FTP
      - '2222:2222' # SSH 2222
      - '2223:2223' # SSH 2223
      - '2224:2224' # SSH 2224
    networks:
      default:
      #directnet: # needed so the proxy service/app can have it's own IP
        #ipv4_address: ${MACNETADDR}
    restart: unless-stopped
#
# need dockerproxy for auto mapping security
# see: https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - POST=0
#
#
#
#
#
#
networks:
  default:
    name: ${CONNET}
    external: true
  #directnet: # needed so the proxy service/app can have it's own IP
    #name: ${MACNET}
    #external: true