#
# https://docs.linuxserver.io/images/docker-swag
#
--- 
version: '3.7'
services:
#
# need dockerproxy for auto mapping security
# see: https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: swag-dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - POST=0
#
#
#
networks:
  default:
    name: ${CONNET}
    external: true
  #directnet: # needed so the proxy service/app can have it's own IP
    #name: ${MACNET}
    #external: true