#
# https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy
#
--- 
version: '3.7'
services:
#
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    privileged: true
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=1
      - SECRETS=1
      - POST=1 # Watchtower
      # Not always needed
      - BUILD=1
      - COMMIT=1
      - CONFIGS=1
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=1
      - EXEC=1
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=1
      - PLUGINS=1
      - SERVICES=1 # Portainer
      - SESSION=1
      - SWARM=0
      - SYSTEM=1
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer
#
networks:
  default:
    name: ${CONNET}
    external: true