#
# https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy
#
--- 
version: '3.7'
services:
#
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - POST=1
#
networks:
  default:
    name: ${CONNET}
    external: true